services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
      - migrate
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_NAME: ${POSTGRES_NAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
      REDIS_ADDR: redis:${REDIS_PORT}
      API_KEY: ${API_KEY}
      SERVER_PORT: ${SERVER_PORT}
    networks:
      - mynetwork

  redis:
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migration
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_NAME: ${POSTGRES_NAME}
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
